import sys
from kb import KB, Boolean, Integer, Constant

# Define our propositional symbols
# J1 is true if the card with index 1 is a jack, etc
# You need to initialise all variables that you need for you strategies and game knowledge.
# Add those variables here.. The following list is complete for the Play Jack strategy.
J0 = Boolean('j0')
J1 = Boolean('j1')
J2 = Boolean('j2')
J3 = Boolean('j3')
J4 = Boolean('j4')
J5 = Boolean('j5')
J6 = Boolean('j6')
J7 = Boolean('j7')
J8 = Boolean('j8')
J9 = Boolean('j9')
J10 = Boolean('j10')
J11 = Boolean('j11')
J12 = Boolean('j12')
J13 = Boolean('j13')
J14 = Boolean('j14')
J15 = Boolean('j15')
J16 = Boolean('j16')
J17 = Boolean('j17')
J18 = Boolean('j18')
J19 = Boolean('j19')
PJ0 = Boolean('pj0')
PJ1 = Boolean('pj1')
PJ2 = Boolean('pj2')
PJ3 = Boolean('pj3')
PJ4 = Boolean('pj4')
PJ5 = Boolean('pj5')
PJ6 = Boolean('pj6')
PJ7 = Boolean('pj7')
PJ8 = Boolean('pj8')
PJ9 = Boolean('pj9')
PJ10 = Boolean('pj10')
PJ11 = Boolean('pj11')
PJ12 = Boolean('pj12')
PJ13 = Boolean('pj13')
PJ14 = Boolean('pj14')
PJ15 = Boolean('pj15')
PJ16 = Boolean('pj16')
PJ17 = Boolean('pj17')
PJ18 = Boolean('pj18')
PJ19 = Boolean('pj19')
A0 = Boolean('A0')
A1 = Boolean('A1')
A2 = Boolean('A2')
A3 = Boolean('A3')
A4 = Boolean('A4')
A5 = Boolean('A5')
A6 = Boolean('A6')
A7 = Boolean('A7')
A8 = Boolean('A8')
A9 = Boolean('A9')
A10 = Boolean('A10')
A11 = Boolean('A11')
A12 = Boolean('A12')
A13 = Boolean('A13')
A14 = Boolean('A14')
A15 = Boolean('A15')
A16 = Boolean('A16')
A17 = Boolean('A17')
A18 = Boolean('A18')
A19 = Boolean('A19')
PA0 = Boolean('pA0')
PA1 = Boolean('pA1')
PA2 = Boolean('pA2')
PA3 = Boolean('pA3')
PA4 = Boolean('pA4')
PA5 = Boolean('pA5')
PA6 = Boolean('pA6')
PA7 = Boolean('pA7')
PA8 = Boolean('pA8')
PA9 = Boolean('pA9')
PA10 = Boolean('pA10')
PA11 = Boolean('pA11')
PA12 = Boolean('pA12')
PA13 = Boolean('pA13')
PA14 = Boolean('pA14')
PA15 = Boolean('pA15')
PA16 = Boolean('pA16')
PA17 = Boolean('pA17')
PA18 = Boolean('pA18')
PA19 = Boolean('pA19')

# Create a new knowledge base
kb = KB()

# GENERAL INFORMATION ABOUT THE CARDS
# This adds information which cards are Jacks
kb.add_clause(J4)
kb.add_clause(J9)
kb.add_clause(J14)
kb.add_clause(J19)
kb.add_clause(A0)
kb.add_clause(A5)
kb.add_clause(A10)
kb.add_clause(A15)
# Add here whatever is needed for your strategy.

# DEFINITION OF THE STRATEGY
# Add clauses (This list is sufficient for this strategy)
# PJ is the strategy to play jacks first, so all we need to model is all x PJ(x) <-> J(x),
# In other words that the PJ strategy should play a card when it is a jack
kb.add_clause(~J4, PJ4)
kb.add_clause(~J9, PJ9)
kb.add_clause(~J14, PJ14)
kb.add_clause(~J19, PJ19)
kb.add_clause(~PJ4, J4)
kb.add_clause(~PJ9, J9)
kb.add_clause(~PJ14, J14)
kb.add_clause(~PJ19, J19)
# Add here other strategies
kb.add_clause(~A0, PA0)
kb.add_clause(~A5, PA5)
kb.add_clause(~A10, PA10)
kb.add_clause(~A15, PA15)
kb.add_clause(~PA0, A0)
kb.add_clause(~PA5, A5)
kb.add_clause(~PA10, A10)
kb.add_clause(~PA15, A15)

# kb.add_clause(~PJ4)
kb.add_clause(~PA0)
# print all models of the knowledge base
for model in kb.models():
    print(model)

# print out whether the KB is satisfiable (if there are no models, it is not satisfiable)
print(kb.satisfiable())
